version: '3.8'

services:

  bd:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: eventos_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - datos-mysql:/var/lib/mysql
    networks:
      - red-eventos
  aplicacion:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    depends_on:
      - bd
    volumes:
      - .:/app
    networks:
      - red-eventos
volumes:
  datos-mysql:

networks:
  red-eventos:
    driver: bridge